#!/usr/bin/perl
## Add internal node names from table generated by MEGA to newick 

use strict;
use Bio::Phylo::IO;


#my $tree_file = "C:/Users/weidewind/Documents/CMD/Coevolution/Influenza/KseniaTrees/little_ksu/nointernals/h1.likelihoods.megaexported.newick";
# my $hashfile = "C:/Users/weidewind/Documents/CMD/Coevolution/Influenza/KseniaTrees/little_ksu/nointernals/h1.likelihoods.megaexported.table";
# my $outfile = "C:/Users/weidewind/Documents/CMD/Coevolution/Influenza/KseniaTrees/little_ksu/nointernals/h1.likelihoods.megaexported.withinternals.newick";

my $tree_file = "C:/Users/weidewind/Documents/CMD/Coevolution/Influenza/aspens/phyloArtifactsCheck/n1.ancestor.likelihoods.newick";
my $hashfile = "C:/Users/weidewind/Documents/CMD/Coevolution/Influenza/aspens/phyloArtifactsCheck/n1.ancestor.likelihoods.table.tree";
my $outfile = "C:/Users/weidewind/Documents/CMD/Coevolution/Influenza/aspens/phyloArtifactsCheck/n1.ancestor.likelihoods.withinternals.newick";
open TREE, "<$tree_file" or die "Cannot open file ".$tree_file."\n";

my $tree_string;
my $t;
while($t = <TREE>){
	$t =~ s/\n$//;
	$tree_string = $tree_string.$t;
}
close TREE;

my $tree = Bio::Phylo::IO->parse(
  -string => $tree_string,
  -format => 'newick'
)->first;


my %parent_hash;
open HASH, "<$hashfile " or die "Cannot open file ".$hashfile ."\n";
my $h = <HASH>;
while(<HASH>){
	my ($parent, $child1, $child2) = split(', ', $_);
	$child1 =~ s/^\s+//;
	$child2 =~ s/^\s+//;
	$child1 =~ s/\s+/_/; 
	$child2 =~ s/\s+/_/; 
	if ($parent =~ /^[0-9]+$/){
		$parent = "Node_".$parent;
	}
	if ($child1 =~ /^[0-9]+$/){
		$child1 = "Node_".$child1;
	}
	if ($child2 =~ /^[0-9]+$/){
		$child2 = "Node_".$child2;
	}
	$parent_hash{$child1} = $parent;
	$parent_hash{$child2} = $parent;
}
close HASH;

for my $n (keys %parent_hash){
	print $n." ".$parent_hash{$n}."\n";
}

$tree->visit_depth_first( 
   -post => sub {
        my $node = shift;
		if ($node->is_internal){
			print "childname ".$node->get_child->get_name()."\n";
			print "myname ".$parent_hash{$node->get_child->get_name()}."\n";
			$node->set_name( $parent_hash{$node->get_child->get_name()} );
		}
   } 
);

open OUT, ">$outfile" or die "Cannot open file ".$outfile ."\n";
print OUT $tree->to_newick( '-nodelabels' => 1 );
close OUT;
 
