screen -U -dm -S fdrh3syn_sites bash -c 'perl fdr_single_sites.pl --input little_ksu --state syn --stattype mean --protein h3 --simnumber 1000 --fakenumber 100 --norm countnorm --bigtag fdrtest100_1000; python grep_ss_fdr.py --fdr /export/home/popova/workspace/aspenclust/output/little_ksu/fdrtest100_1000/syn/mostlikely/countnorm --input /export/home/popova/workspace/aspenclust/output/little_ksu/test1000/syn/mostlikely/countnorm --state syn'
 
 
screen -U -dm -S fdraddsyn_sitesandalleles bash -c 'perl fdr_single_sites.pl --input little_ksu --state syn --stattype mean --protein n1pandemic --simnumber 1000  --fakenumber 100 --norm countnorm --bigtag fdrtest100_1000; perl fdr_single_sites.pl --input little_ksu --state syn --stattype mean --protein h1pandemic --simnumber 1000  --fakenumber 100 --norm countnorm --bigtag fdrtest100_1000; python grep_ss_fdr.py --fdr /export/home/popova/workspace/aspenclust/output/little_ksu/fdrtest100_1000/syn/mostlikely/countnorm --input /export/home/popova/workspace/aspenclust/output/little_ksu/test1000/syn/mostlikely/countnorm --state syn; perl fdr_alleles.pl --input little_ksu --state syn --stattype mean --protein n1pandemic --simnumber 1000 --fakenumber 100 --norm countnorm --bigtag fdrtest100_1000; python grep_alleles_fdr.py --fdr /export/home/popova/workspace/aspenclust/output/little_ksu/fdrtest100_1000/syn/mostlikely/countnorm --input /export/home/popova/workspace/aspenclust/output/little_ksu/test1000/syn/mostlikely/countnorm --state syn'

screen -U -dm -S fdr_h3sites bash -c 'perl fdr_single_sites.pl --input knownpass --splits megasplits --state nsyn --stattype mean --protein h3 --simnumber 1000 --fakenumber 100 --bigtag fdrtest100_1000 >fdr_h3sites_log'
python grep_ss_fdr.py --fdr /export/home/popova/workspace/aspenclust/output/knownpass/megasplits/fdrtest100_1000/nsyn/mostlikely/weightnorm --input /export/home/popova/workspace/aspenclust/output/knownpass/megasplits/test1000/nsyn/mostlikely/weightnorm --state nsyn


screen -U -dm -S fdr_h3alleles bash -c 'perl fdr_alleles.pl --input knownpass --splits megasplits --state nsyn --stattype mean --protein h3 --simnumber 1000 --fakenumber 100 --bigtag fdrtest100_1000 >knownpass/megasplits/fdrtest100_1000/nsyn/fdr_h3alleles_log'
python grep_alleles_fdr.py --fdr /export/home/popova/workspace/aspenclust/output/knownpass/megasplits/fdrtest100_1000/nsyn/mostlikely/weightnorm --input /export/home/popova/workspace/aspenclust/output/knownpass/megasplits/test1000/nsyn/mostlikely/weightnorm --state nsyn'